baseURL = "https://poopcolor.info/"
languageCode = "en-us"
title = "Poo Colour Decoder"
disableKinds = ["taxonomy"]
enableRobotsTXT = false

[params]
  paginationPagerSize = 10

[outputs]
  home = ["HTML", "RSS", "SITEMAP"]

[markup.goldmark.renderer]
  unsafe = true