disableKinds = ["taxonomy", "taxonomyTerm"]

baseURL = "https://poo-color-decoder.netlify.app/"
languageCode = "en-us"
title = "Poo Colour Decoder"
enableRobotsTXT = true

[params]
  paginationPagerSize = 10